language: python

python:
  - "3.5"
  - "3.6"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database flask_jwt_auth_test;' -U postgres

script:
  - python manage.py cov

after_success:
  coveralls
